const standardPermissionsList = [
  'approximate location (network-based)',
  'precise location (GPS and network-based)',
  'retrieve running apps',
  'find accounts on the device',
  'add or remove accounts',
  'read your own contact card',
  'read calendar events plus confidential information',
  'add or modify calendar events and send email to guests without owners\' knowledge',
  'find accounts on the device',
  'read your contacts',
  'modify your contacts',
  'directly call phone numbers',
  'read call log',
  'read phone status and identity',
  'read the contents of your USB storage',
  'modify or delete the contents of your USB storage',
  'take pictures and videos',
  'record audio',
  'view Wi-Fi connections',
  'view network connections',
  'create accounts and set passwords',
  'read battery statistics',
  'pair with Bluetooth devices',
  'access Bluetooth settings',
  'send sticky broadcast',
  'change network connectivity',
  'connect and disconnect from Wi-Fi',
  'full network access',
  'change your audio settings',
  'control Near Field Communication',
  'read sync settings',
  'run at startup',
  'reorder running apps',
  'draw over other apps',
  'control vibration',
  'prevent device from sleeping',
  'toggle sync on and off',
  'install shortcuts',
  'read Google service configuration'
  // Add more standard permissions as needed
];

module.exports = standardPermissionsList;